version: '3.8'

volumes:
  postgres_volumes:

services:
  gophermart:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgres://${PG_USER}:${PG_PASSWORD}@localhost:{PG_PORT}/${PG_DATABASE_NAME}
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "5432:5432"