// Code generated by MockGen. DO NOT EDIT.
// Source: balance_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Makovey/gophermart/internal/repository/model"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockBalancesServiceRepository is a mock of BalancesServiceRepository interface.
type MockBalancesServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalancesServiceRepositoryMockRecorder
}

// MockBalancesServiceRepositoryMockRecorder is the mock recorder for MockBalancesServiceRepository.
type MockBalancesServiceRepositoryMockRecorder struct {
	mock *MockBalancesServiceRepository
}

// NewMockBalancesServiceRepository creates a new mock instance.
func NewMockBalancesServiceRepository(ctrl *gomock.Controller) *MockBalancesServiceRepository {
	mock := &MockBalancesServiceRepository{ctrl: ctrl}
	mock.recorder = &MockBalancesServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalancesServiceRepository) EXPECT() *MockBalancesServiceRepositoryMockRecorder {
	return m.recorder
}

// DecreaseUsersBalance mocks base method.
func (m *MockBalancesServiceRepository) DecreaseUsersBalance(ctx context.Context, userID string, withdraw decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseUsersBalance", ctx, userID, withdraw)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseUsersBalance indicates an expected call of DecreaseUsersBalance.
func (mr *MockBalancesServiceRepositoryMockRecorder) DecreaseUsersBalance(ctx, userID, withdraw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseUsersBalance", reflect.TypeOf((*MockBalancesServiceRepository)(nil).DecreaseUsersBalance), ctx, userID, withdraw)
}

// GetUsersBalance mocks base method.
func (m *MockBalancesServiceRepository) GetUsersBalance(ctx context.Context, userID string) (model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersBalance", ctx, userID)
	ret0, _ := ret[0].(model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersBalance indicates an expected call of GetUsersBalance.
func (mr *MockBalancesServiceRepositoryMockRecorder) GetUsersBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersBalance", reflect.TypeOf((*MockBalancesServiceRepository)(nil).GetUsersBalance), ctx, userID)
}

// RecordUsersWithdraw mocks base method.
func (m *MockBalancesServiceRepository) RecordUsersWithdraw(ctx context.Context, userID, orderID string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordUsersWithdraw", ctx, userID, orderID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordUsersWithdraw indicates an expected call of RecordUsersWithdraw.
func (mr *MockBalancesServiceRepositoryMockRecorder) RecordUsersWithdraw(ctx, userID, orderID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUsersWithdraw", reflect.TypeOf((*MockBalancesServiceRepository)(nil).RecordUsersWithdraw), ctx, userID, orderID, amount)
}
